taskproject/taskapp/urls.py
from django.urls import path
from . import views
app_name='taskapp'
urlpatterns = [
    path('',views.home,name='home'),
    path('log',views.log,name='log'),
    path('regis',views.regis,name='regis'),
    path('lout',views.lout,name='lout'),
    path('allcat',views.allcat,name='allcat'),
    path('detail',views.detail,name='detail'),
    path('load-branches',views.load_branches,name='ajax_load_branches'),
    path('info',views.info,name='info')
    # path('new',views.neww,name='neww')


]

taskproject/taskproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from taskproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("taskapp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

taskproject/taskapp/models.py
from django.db import models
from django.urls import reverse


class branch(models.Model):
    name = models.CharField(max_length=300)
    add = models.URLField(unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'branch'
        verbose_name_plural = 'branches'


    def __str__(self):
        return self.name

class place(models.Model):
    pname= models.CharField(max_length=250)
    branch = models.ForeignKey(branch, on_delete=models.CASCADE)

    class Meta:
         ordering = ('pname',)
         verbose_name = 'place'
         verbose_name_plural = 'places'

    def __str__(self):
        return self.pname


class item(models.Model):
    product=models.CharField(max_length=250)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField(blank=False)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('product',)
        verbose_name = 'item'
        verbose_name_plural = 'items'

    def __str__(self):
        return '{}'.format(self.product)


class userdetail(models.Model):
    name=models.CharField(max_length=250)
    ph=models.IntegerField()
    email=models.TextField(unique=False)
    add=models.TextField()
    prod = models.CharField(max_length=250)
    place = models.CharField(max_length=250)
    quantity=models.IntegerField()
    date_add = models.DateTimeField(auto_now_add=True)
    delivery=models.DateTimeField(auto_now_add=False)
    class Meta:
        db_table = 'userdetail'


    def __str__(self):
        return '{}'.format(self.name)

# class demo(models.Model):
#     name=models.CharField(max_length=250)

taskproject/taskapp/views.py
from datetime import datetime, timedelta

from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from taskapp.models import branch, place, userdetail, item


def home(request):
    br = branch.objects.all()
    return render(request,"home.html",{'branch':br})
def log(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('taskapp:allcat')
        else:
            messages.info(request, "Invalid credentials")
            return redirect('taskapp:log')
    return render(request, "login.html")


def regis(request):
    if request.method == 'POST':
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        cpass = request.POST['cpass']
        if password == cpass:
            if User.objects.filter(username=username).exists():
                messages.info(request,"Username already exists")
                return redirect('taskapp:regis')
            elif User.objects.filter(email=email).exists():
                messages.info(request, "Email already exists")
                return redirect('taskapp:regis')
            else:
                user=User.objects.create_user(username=username,first_name=first_name,last_name=last_name,email=email,password=password)
                user.save()
                messages.info(request,"Registation successfull")
                return redirect('taskapp:log')

        else:
            messages.info(request, "Password and confirm password should be same.")
            return redirect('taskapp:regis')
    return render(request,"index.html")


def lout(request):
    auth.logout(request)
    return redirect('taskapp:home')

def allcat(request):
    return render(request,"ask.html")



def detail(request):
    br = branch.objects.all()
    pro=item.objects.all()
    current_time = datetime.now()
    n = 1
    future_time = current_time + timedelta(hours=n)
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        ph = request.POST['ph']
        add = request.POST['add']
        place = request.POST['place']
        productid = request.POST['prod']
        quantity = request.POST['quantity']
        print(quantity)
        productstock  = item.objects.get(id=productid)
        print(productstock)
        if productstock.stock < int(quantity):
            messages.info(request, "Sorry! We don't have enough stock for your order.")
            return redirect('/detail')
        else:
            res = userdetail.objects.create(name=name, email=email, ph=ph, add=add, place=place,
                                            quantity=quantity, delivery=future_time,prod=productid)

            res.save()
            productstock.stock -= int(quantity)
            productstock.save()
            return redirect('taskapp:info')
    return render(request, "index3.html",{'dist': br,'pro':pro})

def load_branches(request):
    place_id=request.GET.get('dist')
    pla=place.objects.filter(branch_id=place_id).all()
    return render(request, "dropdown_list.html",{'place':pla})


# def neww(request):
#     current_time = datetime.now()
#     n = 40
#     future_time = current_time + timedelta(minutes=n)
#     if request.method == 'POST':
#         name = request.POST['name']
#         email = request.POST['email']
#         ph = request.POST['ph']
#         add = request.POST['add']
#         dis = request.POST['dist']
#         place = request.POST['place']
#         quantity = request.POST['quantity']
#         p = request.POST['prod']
#         pr = ''.join([i for i in p if not i.isdigit()])
#         pro = item.objects.get(product=pr)
#         if quantity > item.pro.stock:
#             messages.info(request, "Please choose less quantity")
#             return redirect('taskapp:detail')
#         else:
#             res = userdetail.objects.create(name=name, email=email, ph=ph, add=add, prod=pr, place=place,
#                                             quantity=quantity, delivery=future_time)
#             res.save()
#     return render(request,"index3.html")
def info(request):
    current_time = datetime.now()
    n = 40
    future_time = current_time + timedelta(minutes=n)
    return render(request,"info.html",{'time':future_time})

taskproject/templates/ask.html
{%load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static 'https://fonts.googleapis.com/css?family=Roboto+Mono:100i,300,300i,400,400i,500,500i,700,700i&display=swap' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Asking form</title>
  </head>
  <body>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br><br>
<center>
    <div>
        <center>
    <h1 style="color:Blue;"><i>Do you wish to order now?</i></h1>
        </center>
        </div></center>
<br><br>

<center>
    
        <a href="{% url 'taskapp:home' %}"> <input type="submit" value="NO" class="btn btn-danger" style="width:100px;"></a>

    <a href="{% url 'taskapp:detail' %}"> <input type="submit" value="YES" class="btn btn-success" style="width:100px;margin-left:400px;"></a>

    </center>






    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

taskproject/templates/dropdown_list.html
 <option slected value="">Select Branch</option>
 {% for i in place %}
 <option value="{{i.pk}}">{{i.pname}}</option>
 {% endfor %}

taskproject/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">

	<title>Pizza - free responsive website template</title>
	<meta name="keywords" content="">
	<meta name="description" content="">
    <meta name="author" content="templatemo">
    <!-- 
    Pizza Template
    http://www.templatemo.com/preview/templatemo_459_pizza
    -->
    
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- bootstrap -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<!-- font-awesome -->
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<!-- custom -->
	<link rel="stylesheet" href="{% static 'css/templatemo-style.css' %}">
	<!-- google font -->
	<link href='//fonts.googleapis.com/css?family=Signika:400,300,600,700' rel='stylesheet' type='text/css'>
	<link href='//fonts.googleapis.com/css?family=Chewy' rel='stylesheet' type='text/css'>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" >
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>

</head>
<body id="home" data-spy="scroll" data-target=".navbar-collapse">

	<!-- start navigation -->
<!--	<div class="navbar navbar-default navbar-fixed-top" role="navigation">-->
<!--		<div class="container">-->
<!--			<div class="navbar-header">-->
<!--				<button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">-->
<!--					<span class="icon icon-bar"></span>-->
<!--					<span class="icon icon-bar"></span>-->
<!--					<span class="icon icon-bar"></span>-->
<!--				</button>-->
<!--				<a href="#home" class="navbar-brand smoothScroll"><strong>PIZZA</strong></a>-->
<!--			</div>-->
<!--			<div class="collapse navbar-collapse">-->
<!--				<ul class="nav navbar-nav navbar-right">-->
<!--					<li><a href="#home" class="smoothScroll">HOME</a></li>-->
<!--					<li><a href="#about" class="smoothScroll">ABOUT</a></li>-->
<!--					<li><a href="#gallery" class="smoothScroll">GALLERY</a></li>-->
<!--					<li><a href="#contact" class="smoothScroll">CONTACT</a></li>-->
<!--				</ul>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->

	<center><nav class="navbar navbar-expand-lg navbar-light bg-white" style="width:2000px;height:50px;">
  <div class="container-fluid">
	 <left> <a href="#home" style="font-family:pacifico;color:orange;font-size:50px;" class="navbar-brand smoothScroll"><strong><i>DOMINOZ</i></strong></a></left>


<right>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height:70px;">
        <li class="nav-item" style="font-size:25px;">
          <a class="nav-link active" aria-current="page"  style="color:orange;" href="#"><i>Home</i></a>
        </li>
		  {% if user.is_authenticated %}

		  <li class="nav-item dropdown {% if 'taskapp' in request.path %} active {% endif %}" style="font-size:25px;">
         <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color:orange;">
            Branches
          </a>

          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            {% for i in branch %}
            <li><a class="dropdown-item" href="{{i.add}}">{{i.name}}</a></li>

            {% endfor %}

          </ul>
        </li>


		  <li class="nav-item" style="font-size:25px;">
          <a class="nav-link active" aria-current="page" style="color:orange;font-size;20px;" href="{% url 'taskapp:lout' %}"><i>Logout</i></a>
        </li>


			{% else %}
		  <li class="nav-item" style="font-size:25px;">
          <a class="nav-link active" aria-current="page" style="color:orange;" href="{% url 'taskapp:log' %}"><i>Login</i></a>
        </li>
		  <li class="nav-item" style="font-size:25px;">
          <a class="nav-link active" aria-current="page" style="color:orange;" href="{% url 'taskapp:regis' %}"><i>Register</i></a>
        </li>



		  {% endif %}
      </ul>



    </div>
	</right>
  </div>
</nav>
  </center>
	<!-- end navigation -->
 {% if user.is_authenticated %}
	<center><h1 style="color:orange;font-size:20px;"><i>Welcome {{user.first_name}}</i></h1></center>
	<center><a type="button" class="btn btn-outline-warning btn-lg" href="{% url 'taskapp:allcat' %}"><i>ORDER NOW</i></a></center>

	  {% else %}
	  <center><a href="log" class="btn btn-warning"><u><strong><i>Please Login for order Your item</i></strong></u></a></center>

	  {% endif %}
	<!-- start flexslider -->
	<div class="flexslider">
		<ul class="slides">
			<li>
				<img src="{% static 'images/slider-img1.jpg' %}" alt="Pizza Image 1">
				<div class="flex-caption">
					<h2 class="slider-title">We make Pizza</h2>
					<h3 class="slider-subtitle">Fresh, clean, and delicious.</h3>
					<p class="slider-description">Praesent tincidunt neque semper elementum gravida. Donec id euismod magna. Ut erat ligula, malesuada eu quam a, fringilla auctor augue.</p>
				</div>
			</li>
			<li>
				<img src="{% static 'images/slider-img2.jpg' %}" alt="Pizza Image 2">
				<div class="flex-caption">
					<h2 class="slider-title">Freshly Baked Pizza</h2>
					<h3 class="slider-subtitle">Premium Quality, Finest Ingredients</h3>
					<p class="slider-description">Donec id euismod magna. Ut erat ligula, malesuada eu quam a, fringilla auctor augue. Praesent tincidunt neque semper elementum gravida.</p>
				</div>
			</li>
		</ul>
	</div>
	<!-- end flexslider -->
	<br><br><br>

	<!-- start about -->
	<section id="about" class="templatemo-section templatemo-top-130">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<h1 class="text-uppercase">Pizza Shop</h1>
				</div>
				<div class="col-md-6 col-sm-6">					
					<h3 class="text-uppercase padding-bottom-10">Another Baker</h3>
					<p>Pizza responsive web template is provided bytarget="_parent">templatemo</a> website. Feel free to download, adapt, and use this template for your websites. Credit goes to <a rel="nofollow" href="http://pixabay.com" target="_parent">Pixabay</a> for images used in this template.</p>
                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet. Dolore magna aliquam erat volutpat.</p>
					<p>Proin enim sem, ultricies sit amet convallis nec, sodales quis augue. Duis consequat felis ac justo luctus, a cursus tellus pharetra. In ullamcorper gravida enim id pulvinar.</p>
				</div>
				<div class="col-md-6 col-sm-6">
					<img src="{% static 'images/about-img1.jpg' %}" class="img-responsive img-bordered img-about" alt="about img">
				</div>
			</div>
		</div>
	</section>
	<!-- end about -->

	<!-- start gallery -->
	<section id="gallery" class="templatemo-section templatemo-light-gray-bg">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h2 class="text-center text-uppercase">Gallery</h2>
					<hr>
				</div>
				<div class="col-md-4 col-sm-4">
					<div class="gallery-wrapper">
						<img src="{% static 'images/gallery-img1.jpg' %}" class="img-responsive gallery-img" alt="Pizza 1">
						<div class="gallery-des">
							<h3>Curabitur </h3>
							<h5>Cras in ante mattis, elementum nunc sed.</h5>
						</div>
					</div>
				</div>	
				<div class="col-md-4 col-sm-4">
					<div class="gallery-wrapper">
						<img src="{% static 'images/gallery-img2.jpg' %}" class="img-responsive gallery-img" alt="Pizza 2">
						<div class="gallery-des">
							<h3>Lorem ipsum</h3>
							<h5>In ullamcorper gravida enim id pulvinar</h5>
						</div>
					</div>
				</div>
				<div class="col-md-4 col-sm-4">
					<div class="gallery-wrapper">
						<img src="{% static 'images/gallery-img3.jpg' %}" class="img-responsive gallery-img" alt="Pizza 3">
						<div class="gallery-des">
							<h3>Pellentesque</h3>
							<h5>Maecenas efficitur nisi id sapien</h5>
						</div>
					</div>
				</div>
				<div class="col-md-6 col-sm-6">
					<div class="gallery-wrapper">
						<img src="{% static 'images/gallery-img4.jpg' %}" class="img-responsive gallery-img" alt="Pizza 4">
						<div class="gallery-des">
							<h3>Suspendisse</h3>
							<h5>Mauris sit amet augue sit amet risus</h5>
						</div>
					</div>
				</div>
				<div class="col-md-6 col-sm-6">
					<div class="gallery-wrapper">
						<img src="{% static 'images/gallery-img5.jpg' %}" class="img-responsive gallery-img" alt="Pizza 5">
						<div class="gallery-des">
							<h3>Elementum</h3>
							<h5>Maecenas efficitur nisi id sapien</h5>
						</div>
					</div>
				</div>				
			</div>
		</div>
	</section>
	<!-- end gallery -->

	<!-- start contact -->
	<section id="contact" class="templatemo-section">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h2 class="text-uppercase text-center">Contact Us</h2>

					<hr>

					<br><br>
				</div>

				<div class="col-md-2"></div>

				<div class="col-md-2"></div>
				<div class="col-md-4 col-sm-4">
					<h3 class="padding-bottom-10 text-uppercase">Contact</h3>

					<p>
						<i class="fa fa-phone contact-fa"></i> 
						<a href="tel:010-020-0340" class="contact-link">010-020-0340</a>, 
						<a href="tel:080-090-0660" class="contact-link">080-090-0660</a>
					</p>			
					<p><i class="fa fa-envelope-o contact-fa"></i> 
                    	<a href="#" class="contact-link">hello@company.com</a></p>
				</div>
				<div class="col-md-4 col-sm-4">
					<h3 class="text-uppercase">Opening hours</h3>
					<p><i class="fa fa-clock-o contact-fa"></i> 7:00 AM - 11:00 PM</p>
					<p><i class="fa fa-bell-o contact-fa"></i> Monday to Friday and Sunday</p>


			  	</div>

				</div>
			</div>
		</div>
	</section>
	<!-- end contact -->

	<!-- start footer -->
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<p>Copyright &copy; 2084 Company Name</p>
					<hr>
					<ul class="social-icon">
						<li><a href="#" class="fa fa-facebook"></a></li>
						<li><a href="#" class="fa fa-twitter"></a></li>
						<li><a href="#" class="fa fa-instagram"></a></li>
						<li><a href="#" class="fa fa-pinterest"></a></li>
						<li><a href="#" class="fa fa-google"></a></li>
						<li><a href="#" class="fa fa-github"></a></li>
						<li><a href="#" class="fa fa-apple"></a></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
	<!-- end footer -->

	<script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/plugins.js' %}"></script>
	<script src="{% static 'js/smoothscroll.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>


</body>
</html>

taskproject/templates/index3.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <link href="{% static 'https://fonts.googleapis.com/css?family=Roboto+Mono:100i,300,300i,400,400i,500,500i,700,700i&display=swap' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css4/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css4/style.css' %}">
</head>
<body>

    <div class="main">

        <div class="container">
            <form method="POST" class="appointment-form" id="foodform" data-courses-url="{% url 'taskapp:ajax_load_branches' %}">
                {% csrf_token %}
                <h2>Food ordering form</h2>
                <div class="form-group-1">
                    <input type="text" name="name" id="title" placeholder="Enter your Name" required />
                    <input type="email" name="email" id="email" placeholder="Email" required />
                    <input type="number" name="ph" id="phone_number" placeholder="Phone number" required />
                    <input type="text" name="add" id="name" placeholder="Enter your Address" required />
                    <div class="select-list">
                        <select name="dist" id="dist">
                            <option slected value="">Select district</option>
                            {% for i in dist %}
                            <option value="{{i.id}}">{{i.name}}</option>
                            {% endfor %}
                        </select >
                    </div>
                     <div class="select-list">
                        <select name="place" id="place">


                        </select>
                    </div>
                </div>
                <div class="form-group-2">
                    <h3>Product details</h3>
                    <div class="select-list">
                        <select name="prod" id="prod">
                            <option seleected value="">Choose product</option>
                            {% for i in pro %}
                            <option value="{{i.id}}">{{i.product}}/{{i.price}}</option>
                            {% endfor %}
                        </select>
                    </div>
                     <input type="number" name="quantity" id="quantity" placeholder="Enter quantity" required />

                </div>
                {% for m in messages %}
            <h3 style="color:red;">{{m}}</h3>
            {% endfor %}

                   <a href=""> <input type="submit" name="submit" class="btn btn-success" value="Order Now" /></a>
                <br><br>
                   <a href=""> <input type="submit" name="submit"  class="btn btn-danger" value="Cancel" /></a>
                <br><br>
                   <a href="{% url 'taskapp:lout' %}" style="color:blue;font-size:18px;">Click here for Logout</a>
            </form>
        </div>

    </div>

    <!-- JS -->
    <script src="{% static 'vendor4/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js4/main.js' %}"></script>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        $("#dist").change(function () {
        var url = $("#foodform").attr("data-courses-url");
        var branchId = $(this).val();

        $.ajax({
        url: url,
        data: {
            'dist': branchId
            },
            success: function (data) {
                $("#place").html(data);
                }
                });
                });
    </script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

taskproject/templates/info.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static 'https://fonts.googleapis.com/css?family=Roboto+Mono:100i,300,300i,400,400i,500,500i,700,700i&display=swap' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Asking form</title>
  </head>
  <body>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br><br>
<center>
    <div>
        <center>
    <h1 style="color:Blue;"><i>Oder placed successfully.... Your order will be delivered at {{time}}</i></h1>
        </center>
        </div></center>
<br><br>

<center>

        <a href="{% url 'taskapp:lout' %}"> <input type="submit" value="LOGOUT" class="btn btn-danger" style="width:100px;"></a>


    <a href="{% url 'taskapp:home' %}"> <input type="submit" value="OK" class="btn btn-success" style="width:100px;margin-left:400px;"></a>

    </center>






    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

taskproject/templates/login.html
{%load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static 'https://fonts.googleapis.com/css?family=Roboto+Mono:100i,300,300i,400,400i,500,500i,700,700i&display=swap' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'fonts2/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css2/owl.carousel.min.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css2/bootstrap.min.css' %}">
    
    <!-- Style -->
    <link rel="stylesheet" href="{% static 'css2/style.css' %}">


    <title>Login</title>
  </head>
  <body>
  

  <div class="d-lg-flex half">
    <div class="bg order-1 order-md-2" style="background-image: url({% static 'images2/bg_1.jpg' %});"></div>
    <div class="contents order-2 order-md-1">

      <div class="container">
        <div class="row align-items-center justify-content-center">
          <div class="col-md-7">
            <h3><strong>LOGIN</strong></h3>
            <br><br>
            <form action="log" method="post">
              {% csrf_token %}
              <div class="form-group first">
                <label for="username">Username</label>
                <input type="text" class="form-control" placeholder="your username" id="username" name="username" required>
              </div>
              <div class="form-group last mb-3">
                <label for="password">Password</label>
                <input type="password" class="form-control" placeholder="Your Password" id="password" name="password" required>
              </div>
              
              <div class="d-flex mb-5 align-items-center">
{% for m in messages %}
            <h3 style="color:red;">{{m}}</h3>
            {% endfor %}

                </label>
                <span class="ml-auto"><a href="regis" class="forgot-pass">New User?<b>Register</b></a></span>
              </div>

             <a href="{% url 'taskapp:allcat' %}"> <input type="submit" value="Log In" class="btn btn-block btn-primary"></a>

            </form>
          </div>
        </div>
      </div>
    </div>

    
  </div>



    <script src="{% static 'js2/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js2/popper.min.js' %}"></script>
    <script src="{% static 'js2/bootstrap.min.js' %}"></script>
    <script src="{% static 'js2/main.js' %}"></script>
  </body>
</html>